"""add pinned entry-point notes

Revision ID: 0d3836d351ae
Revises: 544a688002a1
Create Date: 2026-07-01 20:15:55.715668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3836d351ae'
down_revision: Union[str, Sequence[str], None] = '544a688002a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        # server_default for existing rows; matches the Python-level default.
        batch_op.add_column(
            sa.Column('pinned', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('pinned')

    # ### end Alembic commands ###
