"""notes redesign: versioning, links, deletion, dashboard fields

Revision ID: 544a688002a1
Revises: f0e0c44a53c1
Create Date: 2026-07-01 12:02:43.382615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544a688002a1'
down_revision: Union[str, Sequence[str], None] = 'f0e0c44a53c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('from_note_id', sa.Integer(), nullable=False),
    sa.Column('to_note_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.LargeBinary(), nullable=False),
    sa.Column('is_bidi', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.identifier'], ),
    sa.ForeignKeyConstraint(['from_note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['to_note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_links_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_from_note_id'), ['from_note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_to_note_id'), ['to_note_id'], unique=False)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.LargeBinary(), nullable=True))
        # Nullable: legacy rows predate this column and can't be backfilled
        # here (computing it needs the per-agent spirit key, which a
        # migration never has). The API layer backfills lazily on next access.
        batch_op.add_column(sa.Column('snippet', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.LargeBinary(), nullable=True))
        # server_default for existing rows; matches the Python-level default.
        batch_op.add_column(
            sa.Column('tags_encrypted', sa.Boolean(), nullable=False, server_default=sa.true())
        )
        batch_op.add_column(sa.Column('supersedes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('superseded_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pending_delete_at', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notes_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_pending_delete_at'), ['pending_delete_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_superseded_by'), ['superseded_by'], unique=False)
        # SQLite batch mode rebuilds the whole table and requires named
        # constraints — autogenerate's `None` (anonymous) doesn't work here.
        batch_op.create_foreign_key('fk_notes_supersedes_notes', 'notes', ['supersedes'], ['id'])
        batch_op.create_foreign_key('fk_notes_superseded_by_notes', 'notes', ['superseded_by'], ['id'])
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('updated_at', sa.FLOAT(), nullable=False, server_default=sa.text('0'))
        )
        batch_op.drop_constraint('fk_notes_supersedes_notes', type_='foreignkey')
        batch_op.drop_constraint('fk_notes_superseded_by_notes', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_notes_superseded_by'))
        batch_op.drop_index(batch_op.f('ix_notes_pending_delete_at'))
        batch_op.drop_index(batch_op.f('ix_notes_agent_id'))
        batch_op.drop_column('pending_delete_at')
        batch_op.drop_column('superseded_by')
        batch_op.drop_column('supersedes')
        batch_op.drop_column('tags_encrypted')
        batch_op.drop_column('tags')
        batch_op.drop_column('snippet')
        batch_op.drop_column('summary')
        batch_op.drop_column('title')

    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_links_to_note_id'))
        batch_op.drop_index(batch_op.f('ix_links_from_note_id'))
        batch_op.drop_index(batch_op.f('ix_links_created_at'))
        batch_op.drop_index(batch_op.f('ix_links_agent_id'))

    op.drop_table('links')
    # ### end Alembic commands ###
