"""baseline

Revision ID: 60fa08d94003
Revises: 
Create Date: 2026-06-30 10:03:00.100120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60fa08d94003'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('vault_salt', sa.LargeBinary(), nullable=False),
    sa.Column('vault_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('vault_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('root_public_key', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('contact_endpoint', sa.String(), nullable=True),
    sa.Column('policy_json', sa.String(), nullable=True),
    sa.Column('pending_policy_json', sa.String(), nullable=True),
    sa.Column('pending_effective_at', sa.Float(), nullable=True),
    sa.Column('pending_created_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('identifier')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('text', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.identifier'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('message', sa.LargeBinary(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.identifier'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('service_hmac', sa.String(), nullable=False),
    sa.Column('service_name', sa.LargeBinary(), nullable=False),
    sa.Column('signing_public_key', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_public_key', sa.LargeBinary(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.identifier'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'service_hmac', name='uq_agent_service')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_keys')
    op.drop_table('notices')
    op.drop_table('notes')
    op.drop_table('agents')
    # ### end Alembic commands ###
