"""add session and challenge tables

Revision ID: cb73d41311a9
Revises: f2ad1fd9b57c
Create Date: 2026-06-30 10:19:36.110213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb73d41311a9'
down_revision: Union[str, Sequence[str], None] = 'f2ad1fd9b57c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_sessions',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('last_used_at', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['identifier'], ['agents.identifier'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('pending_challenges',
    sa.Column('challenge_id', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('expected', sa.String(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('attempts_left', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['identifier'], ['agents.identifier'], ),
    sa.PrimaryKeyConstraint('challenge_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_challenges')
    op.drop_table('active_sessions')
    # ### end Alembic commands ###
