"""add rate limiter tables

Revision ID: f0e0c44a53c1
Revises: cb73d41311a9
Create Date: 2026-06-30 13:37:08.477355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e0c44a53c1'
down_revision: Union[str, Sequence[str], None] = 'cb73d41311a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_backoff',
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('cooldowns', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.Float(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('subject')
    )
    op.create_table('rate_window',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('hit_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rate_window', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_window_subject'), ['subject'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rate_window', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_window_subject'))

    op.drop_table('rate_window')
    op.drop_table('rate_backoff')
    # ### end Alembic commands ###
