"""sync stable to current models

Revision ID: f2ad1fd9b57c
Revises: 60fa08d94003
Create Date: 2026-06-30 10:03:18.119591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ad1fd9b57c'
down_revision: Union[str, Sequence[str], None] = '60fa08d94003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_endpoint', sa.String(), nullable=True))

    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               existing_nullable=False)

    with op.batch_alter_table('service_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_hmac', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('service_name', sa.LargeBinary(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_agent_service'), type_='unique')
        batch_op.create_unique_constraint('uq_agent_service', ['agent_id', 'service_hmac'])
        batch_op.drop_column('service')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('uq_agent_service', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_agent_service'), ['agent_id', 'service'])
        batch_op.drop_column('service_name')
        batch_op.drop_column('service_hmac')

    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('contact_endpoint')

    # ### end Alembic commands ###
